// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96JUzEQbI2vcacSsmxQN_CcoKie95Jac',
    appId: '1:443082098193:web:efe616363d34865b3bd3b0',
    messagingSenderId: '443082098193',
    projectId: 'adhunikyantra-e2dee',
    authDomain: 'adhunikyantra-e2dee.firebaseapp.com',
    databaseURL: 'https://adhunikyantra-e2dee-default-rtdb.firebaseio.com',
    storageBucket: 'adhunikyantra-e2dee.firebasestorage.app',
    measurementId: 'G-36JCZX7EYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRUGXhoE6w010mM1XuAAgVPk0IXmdETtA',
    appId: '1:443082098193:android:3f44d322e9376a7d3bd3b0',
    messagingSenderId: '443082098193',
    projectId: 'adhunikyantra-e2dee',
    databaseURL: 'https://adhunikyantra-e2dee-default-rtdb.firebaseio.com',
    storageBucket: 'adhunikyantra-e2dee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnyxoO3hdtkd8axraG88nWDkEfbodhI0g',
    appId: '1:443082098193:ios:89500df14b8841bb3bd3b0',
    messagingSenderId: '443082098193',
    projectId: 'adhunikyantra-e2dee',
    databaseURL: 'https://adhunikyantra-e2dee-default-rtdb.firebaseio.com',
    storageBucket: 'adhunikyantra-e2dee.firebasestorage.app',
    iosBundleId: 'com.example.adhunikYantra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnyxoO3hdtkd8axraG88nWDkEfbodhI0g',
    appId: '1:443082098193:ios:89500df14b8841bb3bd3b0',
    messagingSenderId: '443082098193',
    projectId: 'adhunikyantra-e2dee',
    databaseURL: 'https://adhunikyantra-e2dee-default-rtdb.firebaseio.com',
    storageBucket: 'adhunikyantra-e2dee.firebasestorage.app',
    iosBundleId: 'com.example.adhunikYantra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB96JUzEQbI2vcacSsmxQN_CcoKie95Jac',
    appId: '1:443082098193:web:e3d80733934eaa813bd3b0',
    messagingSenderId: '443082098193',
    projectId: 'adhunikyantra-e2dee',
    authDomain: 'adhunikyantra-e2dee.firebaseapp.com',
    databaseURL: 'https://adhunikyantra-e2dee-default-rtdb.firebaseio.com',
    storageBucket: 'adhunikyantra-e2dee.firebasestorage.app',
    measurementId: 'G-E890HP4LM6',
  );
}
